### ISSUE TITLE
Add template to AclProviderInterface and MutableAclProviderInterface

### ISSUE THREAD

**Issue by VincentLanglet** [psalm/psalm-plugin-symfony#189]
Hi @seferov !

In order to fix some issues with those interface, phpstan is trying to introduce a template to them with the commit 
https://github.com/phpstan/phpstan-symfony/commit/41fff98845bb8c4c0dc6c56f82b75358e57ccef9

So `@param MutableAclProviderInterface<MutableAclInterface>` will works for phpstan, but psalm will throw an error
```
psalm: TooManyTemplateParams: Symfony\Component\Security\Acl\Model\MutableAclProviderInterface<Symfony\Component\Security\Acl\Model\MutableAclInterface> has too many template params, expecting 0
```

@see https://github.com/phpstan/phpstan-symfony/issues/183

In order to fix this, the same template should be added to this plugin.
Do you agree with this ?

**Comment by seferov** [comment]
Hi @VincentLanglet,

Thanks for the report. These interfaces don't exist in Symfony versions >= 3, right?

**Comment by VincentLanglet** [comment]
> Thanks for the report. These interfaces don't exist in Symfony versions >= 3, right?

They does exist 
https://github.com/symfony/security-acl/blob/main/Model/AclProviderInterface.php
https://github.com/symfony/security-acl/blob/main/Model/MutableAclProviderInterface.php

Phpstan tried to improve the return type of the method `findAcl` and `findAcls`, in order to do something like 
https://github.com/symfony/security-acl/pull/83, but with a template for the AclProviderInterface instead.

I just opened the PR on symfony, and maybe it will avoid to add the stub with this template on both phpstan-symfony and psalm-symfony.

**Comment by ondrejmirtes** [comment]
The whole train of thought here is:

1) `MutableAclProviderInterface::findAcls()` needs to return `SplObjectStorage<ObjectIdentityInterface, MutableAclInterface>`.
2) The naive solution is to provide stubs that look like this: https://psalm.dev/r/976f1398a0 (see the error, same one is reported by PHPStan). This is the current state in phpstan-symfony. No error was reported previously because of a hole in the stubs validation that was closed with: https://github.com/phpstan/phpstan-src/commit/c98d0a4946c373543c379427983e02ccef71f86c. But now the error is reported so I need to solve it.
3) My solution to this problem is to make the interfaces generic (https://github.com/phpstan/phpstan-symfony/commit/41fff98845bb8c4c0dc6c56f82b75358e57ccef9). Which works nicely and even solves another separate issue, but the downside is that the users of these interfaces now need to specify the `@template` types each time the interface is typehinted. Which might be benefitial but also annoying if phpstan-symfony and psalm-plugin-symfony aren't on the same page.

It would be a good idea to get to an agreement and have the same stubs for these interfaces. Thanks!

**Comment by VincentLanglet** [comment]
@ondrejmirtes Does the https://github.com/symfony/security-acl/pull/83 PR could solve the issue directly in symfony ? Or if something need to be done in symfony, it would require a template too ?

**Comment by ondrejmirtes** [comment]
@VincentLanglet It's fine short-term, but once Symfony is analysed with SA, they would bump into the same problem and would have to look for solutions like we do now.

**Comment by ondrejmirtes** [comment]
Also the whole point of this error and solution is to have sound types - there are situations in runtime that can lead to an error with the current typehints. The root problem here is that having a mutable object like `SplObjectStorage` part of the API is a poor choice.

**Comment by VincentLanglet** [comment]
> @VincentLanglet It's fine short-term, but once Symfony is analysed with SA, they would bump into the same problem and would have to look for solutions like we do now.

Sure, the right solution is to add a template. But when developer is looking for information on a class (for instance by clicking on it in Phpstorm), it shows the Symfony class. Having a template in the stub when the original class doesn't have one can be confusing.

I wasn't sure Symfony were ready to use template in his own code ; I don't know if there is one currently. 
So I was thinking that this could be a convenient solution for now, and the day static analysis will step up for Symfony, they will introduce a template in their own code.

**Comment by ondrejmirtes** [comment]
Yeah, that's up to Symfony maintainers to decide.

**Comment by VincentLanglet** [comment]
I think the PR https://github.com/symfony/security-acl/pull/83 will be merged, so it's better to remove the stub/template here

**Comment by VincentLanglet** [comment]
https://github.com/symfony/security-acl/pull/83 was merged
