### ISSUE TITLE
Optionally disable MissingReturnType on actions

### ISSUE THREAD

**Issue by beberlei** [psalm/psalm-plugin-symfony#21]
Its a bit annoying to get around the `MissingReturnType` errors on controller action methods, since they can return many different things (Response, array, any objects depending on view listeners).

Would be nice to have a config to disable `MissingReturnType` if the method is a *Controller::*Action.

**Comment by seferov** [comment]
@beberlei thank you for the report!

I faced the same issue and I see your point. But I think it is better to handle on project level because:
- it is hard to tell if a method is a controller action. For controller method `Action` suffix is not required after Symfony 3 (for example: https://symfony.com/doc/4.4/controller.html).
- it is very easy to suppress on a project level if needed. Example on paslm.xml:
```xml
<issueHandlers>
    <MissingReturnType>
        <errorLevel type="suppress">
            <directory name="src/Controller" />
        </errorLevel>
    </MissingReturnType>
</issueHandlers>
```
