### ISSUE TITLE
check statically container configuration

### ISSUE THREAD

**Issue by marcosh** [psalm/psalm-plugin-symfony#231]
Would it be possible to check statically that arguments of services declared in the container have the correct type?

**Comment by zmitic** [comment]
Why would you want that? Compiled container is not under your control, and there is nothing you can do about it.

**Comment by marcosh** [comment]
I mean, if I configure the container incorrectly, I will get errors. I would like to avoid that.

For example, if I have a service

```php
class Foo
{
    public function __construct(Bar $bar) {...}
}
```

and it is configured as

```xml
<service id="Foo" class="Foo">
    <argument type="service" id="Bar"/> --> service Bar refers to a class Bar
</service>
```

I will get an error when I run my application. I would like to prevent that error statically, before running the application in any way.

I'm not a Symfony expert, so there might be something I'm missing.

**Comment by zmitic** [comment]
Got it!

For a start, you shouldn't be doing manual wiring; use autowiring instead. Not only it is recommended by Symfony, it will also save you **lots** of time.

But even with manual setup, it won't work. If you miss-configure xml/yaml, container **won't be compiled**. So there is nothing to check, it might even tell you it is OK because it analyzed old file but new wasn't generated.

Static analysis of xaml/yaml is never going to happen, it would require new parser that mimics all of the functionalities in Symfony. Just take form extensions or messenger handlers and you will see why it is not possible.

**Comment by marcosh** [comment]
Thanks @zmitic for the explanation. Closing the issue
