### ISSUE TITLE
More stubs?

### ISSUE THREAD

**Issue by zerkms** [psalm/psalm-plugin-symfony#41]
Hey team, what's the aim for this project? I see at the moment it's one stub there.

I've built a small collection (just 4, but still) of stubs here https://github.com/zerkms/symfony-psalm-plugin/tree/master/stubs

I'd rather contribute to other project than maintain a half-dead mine.

Hence a question: would my stubs be welcome if I PR them here?

And if "yes" - have you already thought how to version stubs from different symfony versions?

**Comment by seferov** [comment]
Hey @zerkms,

The aim of this plugin is to make Psalm understand Symfony framework better.
Since Symfony, the framework and components, is well-written and documented (mostly phpdoc) there is no need for stubs as far as I can see (we are using psalm on several large Symfony projects).
On the other hand, the need is more on things like dependency injection, console options & arguments, dynamic return types based on arguments, Doctrine repositories, enforcing best practices, etc. These cannot be solved with stubs.

Your contributions are more than welcome. For different Symfony versions I think stubs or hooks can be registered by checking `\Symfony\Component\HttpKernel\Kernel::VERSION_ID` const.

**Comment by zerkms** [comment]
> there is no need for stubs as far as I can see

oh, I wish this was true :-D

For instance see this stub: https://github.com/zerkms/symfony-psalm-plugin/blob/master/stubs/FormView.php 

And a corresponding discussion (it's a long thread there): https://github.com/symfony/symfony/pull/32205

**Comment by zerkms** [comment]
One more question then: why `.stubphp`?

**Comment by seferov** [comment]
Yes, since we don't use Symfony Forms I was not aware of that.
Could you please make PR for it? It would be better if you could provide tests as well.

> One more question then: why .stubphp?

PHPStorm or other IDEs won't treat them as PHP files. See https://github.com/psalm/psalm-plugin-laravel/issues/43

**Comment by zerkms** [comment]
> Could you please make PR for it? It would be better if you could provide tests as well.

Totally. I will then familiarise with the code quality requirements of this project and probably some day next week will port my stubs here.

Thanks! :-)
